### ISSUE TITLE
__dirname used over process.cwd()

### ISSUE THREAD

**Issue by chrisblossom** [tribou/jest-serializer-path#9]
Is there a reason ``__dirname`` is used to find the project root instead of ``process.cwd()``? This is causing some issues with a tool I'm using and I was wondering if you'd accept a PR that switched to ``process.cwd()``?

https://github.com/tribou/jest-serializer-path/blob/05c64e41a9a59c08e20b446688acd77fd8687afd/lib/index.js#L9-L11

**Comment by tribou** [comment]
Sure, I would be open to a PR 👍
